better canvas gen
robertkozin/discord-video-preview-bot pull request #7
Opened 2023-07-06 04:49 UTC by nathanielfernandes

2023-07-07 01:08 UTC, robertkozin requested changes
Can you also please look at the Dockerfile and increment the cache bust thing, you'll see it

2023-07-07 01:08 UTC, robertkozin commented on main.go
> +var previewGenCode = func() string {
Please use https://pkg.go.dev/embed to embed files into code

2023-07-07 01:08 UTC, robertkozin commented on main.go
> +	os.MkdirAll(tempDir, os.ModePerm)
Deplicate line

2023-07-07 01:08 UTC, robertkozin commented on main.go
> +	token.StartAccessTokenReferesher()
Duplicate lines

2023-07-07 01:08 UTC, robertkozin commented on preview.ql
> +}
New line

2023-07-07 02:33 UTC, nathanielfernandes commented
done 👍🏽

2023-07-08 05:53 UTC, robertkozin approved these changes

2023-07-08 05:53 UTC, merged